import './globals.css'
import Layout from '@/components/Layout'

export const metadata = {
  title: 'TOYOKOUWORKS 2023',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ja'>
      <Layout>{children}</Layout>
    </html>
  )
}
